services:
  mongo:
    image: mongo:latest
    container_name: recruiting-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME:
      MONGO_INITDB_ROOT_PASSWORD:
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: ./recruiting-api
    container_name: recruiting-api
    restart: always
    environment:
      MONGO_URI:
      PORT:
    ports:
      - "5000:5000"
    depends_on:
      - mongo

volumes:
  mongo_data:
